# 60 realistic inbound messages for a fictional SaaS company, hand-labelled.
# team: billing | technical | sales | cancellation | spam
# churn: True if the sender is plausibly about to leave / downgrade
INBOX = [
    # --- billing ---
    ("I was charged twice for my September invoice. Can you refund the duplicate?", "billing", False),
    ("Where can I download a PDF of last month's invoice for my accountant?", "billing", False),
    ("Our company card expired, how do I update payment details before renewal?", "billing", False),
    ("Can you add our VAT number to the invoices? We're based in Germany.", "billing", False),
    ("Why did my bill go from $49 to $79 this month?? Nobody told us about a price change.", "billing", True),
    ("Please change the billing email to finance@ourco.com", "billing", False),
    ("We paid by wire transfer 10 days ago but the account still says overdue.", "billing", False),
    ("Is it possible to switch from monthly to annual billing and get the discount?", "billing", False),
    ("I got a receipt for a seat I removed last week. Should that be prorated?", "billing", False),
    ("Third time asking: refund the charge from the 3rd. If this isn't sorted by Friday we're disputing it with the bank.", "billing", True),
    ("Do you accept purchase orders? Our procurement team requires one.", "billing", False),
    ("The invoice has our old company name on it, can it be reissued?", "billing", False),
    # --- technical ---
    ("Dashboard has been stuck on 'loading' since this morning for our whole team.", "technical", False),
    ("The CSV export cuts off at 10,000 rows. Is that a bug or a limit?", "technical", False),
    ("SSO login with Okta returns error 403 after the latest update.", "technical", False),
    ("Webhooks stopped firing yesterday around 4pm UTC. Nothing changed on our side.", "technical", False),
    ("How do I connect the API to Zapier? The docs link is broken.", "technical", False),
    ("Your mobile app crashes every time I open the reports tab on Android 15.", "technical", False),
    ("Honestly the app has been down so often this month I'm looking at alternatives. Is it fixed now?", "technical", True),
    ("Getting 'rate limit exceeded' on the API even though we're way under 100 req/min.", "technical", False),
    ("Can't reset my password, the reset email never arrives.", "technical", False),
    ("Charts show the wrong timezone, everything is shifted by 2 hours.", "technical", False),
    ("Is there a way to bulk import contacts from HubSpot?", "technical", False),
    ("Data from the last sync is missing. This is the second time we've lost data. Not acceptable.", "technical", True),
    # --- sales ---
    ("We're a 300-person company evaluating tools like yours. Can we book a demo?", "sales", False),
    ("Do you offer discounts for nonprofits?", "sales", False),
    ("What's the difference between the Pro and Business plans?", "sales", False),
    ("We want to add 40 more seats. Can someone send a quote?", "sales", False),
    ("Does the Enterprise plan include a dedicated account manager and SLA?", "sales", False),
    ("Are you SOC 2 compliant? Our security team needs the report before we buy.", "sales", False),
    ("Could we get a 30 day trial extension? Still convincing my boss.", "sales", False),
    ("Is there an education discount for universities?", "sales", False),
    ("Loving the product! We'd like to roll it out to the marketing team too, what are our options?", "sales", False),
    ("Your competitor offered us 40% off. Can you match it or we'll go with them at renewal.", "sales", True),
    ("Can we get a custom contract with a data processing agreement?", "sales", False),
    ("Do you have a partner/reseller program for agencies?", "sales", False),
    # --- cancellation ---
    ("Please cancel our subscription at the end of the current term.", "cancellation", True),
    ("How do I delete my account and all my data?", "cancellation", True),
    ("We're downgrading to the free plan, the paid features aren't worth it for us.", "cancellation", True),
    ("We've decided to move to another platform. What's the process to export everything and close the account?", "cancellation", True),
    ("Our startup is shutting down, please stop all future charges.", "cancellation", True),
    ("Pause our account for 3 months? We don't need it over summer.", "cancellation", True),
    ("I didn't mean to renew. Cancel and refund please.", "cancellation", True),
    ("Remove auto-renewal from our plan, we'll decide next month whether to continue.", "cancellation", True),
    ("Team voted to consolidate tools. Yours is the one going. How do we wind down?", "cancellation", True),
    ("Cancel. Just cancel. I'm done.", "cancellation", True),
    # --- spam ---
    ("Boost your SEO ranking to #1 on Google in 7 days! Reply for a free audit.", "spam", False),
    ("Dear sir, I am a prince with $4.5M waiting for transfer, please send bank details.", "spam", False),
    ("We noticed your website could use a redesign. Our agency offers 50% off this week.", "spam", False),
    ("Congratulations!! You have been selected for an exclusive crypto giveaway.", "spam", False),
    ("Hi, are you the right person to talk to about outsourcing your lead generation?", "spam", False),
    ("Get 10,000 Instagram followers for just $9.99", "spam", False),
    ("Quick question about guest posting on your blog, we pay $50 per link.", "spam", False),
    ("URGENT: your mailbox storage is full, click here to verify your account.", "spam", False),
    # --- tricky / mixed intent ---
    ("Great product, terrible support. Been waiting 5 days on a ticket about a broken integration.", "technical", True),
    ("If you can't fix the export bug this week, please just cancel us.", "cancellation", True),
    ("Before we renew, can you confirm whether the price increase applies to annual plans?", "billing", False),
    ("Our CFO wants to know if there's a cheaper plan, otherwise we'll probably cancel.", "sales", True),
    ("Wow, another outage. Love paying for this. 🙃", "technical", True),
    ("Loving the new update! Is the new API included on the Business plan or only Enterprise?", "sales", False),
]
